// RomM platform slug -> ES-DE / EmuDeck rom folder names (first match that exists wins,
// otherwise the first entry is used as the default folder name).
module.exports = {
  '3do': ['3do'],
  'acpc': ['amstradcpc'],
  'amiga': ['amiga'],
  'amiga-cd32': ['amigacd32', 'cd32'],
  'android': ['android'],
  'arcade': ['arcade', 'mame', 'fbneo'],
  'arduboy': ['arduboy'],
  'atari2600': ['atari2600'],
  'atari5200': ['atari5200'],
  'atari7800': ['atari7800'],
  'atari800': ['atari800'],
  'atari-st': ['atarist'],
  'jaguar': ['atarijaguar'],
  'atari-jaguar-cd': ['atarijaguarcd'],
  'lynx': ['atarilynx'],
  'atomiswave': ['atomiswave'],
  'c64': ['c64'],
  'colecovision': ['colecovision'],
  'cps1': ['cps1', 'arcade'],
  'cps2': ['cps2', 'arcade'],
  'cps3': ['cps3', 'arcade'],
  'dc': ['dreamcast', 'dc'],
  'dos': ['dos', 'pc'],
  'fds': ['fds'],
  'famicom': ['famicom', 'nes'],
  'game-and-watch': ['gameandwatch'],
  'gamegear': ['gamegear'],
  'gb': ['gb'],
  'gba': ['gba'],
  'gbc': ['gbc'],
  'ngc': ['gc', 'gamecube'],
  'gc': ['gc', 'gamecube'],
  'genesis-slash-megadrive': ['genesis', 'megadrive'],
  'genesis': ['genesis', 'megadrive'],
  'megadrive': ['megadrive', 'genesis'],
  'intellivision': ['intellivision'],
  'mega-duck-slash-cougar-boy': ['megaduck'],
  'msx': ['msx'],
  'msx2': ['msx2'],
  'n64': ['n64'],
  '64dd': ['n64dd'],
  'nds': ['nds'],
  'nintendo-dsi': ['nds'],
  '3ds': ['n3ds', '3ds'],
  'n3ds': ['n3ds', '3ds'],
  'new-nintendo-3ds': ['n3ds', '3ds'],
  'naomi': ['naomi'],
  'naomi2': ['naomi2'],
  'neogeoaes': ['neogeo'],
  'neogeomvs': ['neogeo'],
  'neo-geo-cd': ['neogeocd'],
  'neo-geo-pocket': ['ngp'],
  'neo-geo-pocket-color': ['ngpc'],
  'nes': ['nes'],
  'ngage': ['ngage'],
  'odyssey-2': ['odyssey2'],
  'pc-fx': ['pcfx'],
  'pc-8800-series': ['pc88'],
  'pc-9800-series': ['pc98'],
  'pico-8': ['pico8'],
  'pokemon-mini': ['pokemini'],
  'ps': ['psx', 'ps1'],
  'psx': ['psx', 'ps1'],
  'ps2': ['ps2'],
  'ps3': ['ps3'],
  'ps4': ['ps4'],
  'psp': ['psp'],
  'psvita': ['psvita'],
  'saturn': ['saturn'],
  'scummvm': ['scummvm'],
  'sega-pico': ['pico'],
  'sega32': ['sega32x'],
  'sega-32x': ['sega32x'],
  'segacd': ['segacd', 'megacd'],
  'sg1000': ['sg-1000', 'sg1000'],
  'sms': ['mastersystem'],
  'snes': ['snes'],
  'sfam': ['sfc', 'snes'],
  'supervision': ['supervision'],
  'switch': ['switch'],
  'tic-80': ['tic80'],
  'turbografx16--1': ['pcengine', 'tg16'],
  'tg16': ['pcengine', 'tg16'],
  'turbografx-16-slash-pc-engine-cd': ['pcenginecd', 'tg-cd'],
  'vectrex': ['vectrex'],
  'virtualboy': ['virtualboy'],
  'wii': ['wii'],
  'wiiu': ['wiiu'],
  'win': ['windows'],
  'windows': ['windows'],
  'wonderswan': ['wonderswan'],
  'wonderswan-color': ['wonderswancolor'],
  'x68000': ['x68000'],
  'xbox': ['xbox'],
  'xbox360': ['xbox360'],
  'zxs': ['zxspectrum'],
  'zx81': ['zx81'],
};
