// Builds electron/emuSettingsDb.json: every setting each emulator takes in a game's own settings file, read from the
// emulators' source (0.9.61, owner: PPSSPP's list was wrong, Dolphin's missed most; then "across the board"). One
// reader per emulator in readers/ (what it reads and where from: its `files`, notes in docs/game-settings/<emu>.md).
// Each entry: { s: section as the game's file writes it, k: key, t: bool|int|float|enum|text, d: default as written,
// o: [[value, label]], min, max, l: the emulator's own name for it, desc, tab, adv: advanced (goes in Advanced) }.
// Usage: node tools/game-settings/gen.js --fetch <sources folder>   (downloads each reader's files into <folder>/<id>, and
//        each release's into <folder>/<id>@<tag>; --tags-only fetches only the releases)
//        node tools/game-settings/gen.js <sources folder>
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const fetch = process.argv[2] === '--fetch';
const root = process.argv.filter((a) => !a.startsWith('--'))[2];
if (!root) { console.error('usage: node tools/game-settings/gen.js [--fetch] <sources folder>'); process.exit(1); }
const readers = fs.readdirSync(path.join(__dirname, 'readers')).filter((f) => f.endsWith('.js')).sort().map((f) => require(path.join(__dirname, 'readers', f)));
// 0.9.63 (owner: Eden 0.2.0 shows three GPU Modes, Cartridge offered two, and 1 meant Balanced, not Accurate): the
// settings of each emulator's last releases too, not only its newest source. A reader's `versions` names its git
// repository and which tags are releases; the same files are fetched at each tag (<root>/<id>@<tag>/) and only what
// differs from the newest is kept (db.versions[id]): Cartridge picks the release you have installed.
const KEEP = 4;
const natural = (a, b) => a.localeCompare(b, 'en', { numeric: true });
// a file of the emulator's own repository, at a tag (a file from another repository stays as it is)
const urlAt = (url, tag, git) => { const [o, n] = String(git).replace(/\.git$/, '').split('/').slice(-2); return !url.toLowerCase().includes(`/${o}/${n}/`.toLowerCase()) ? url : urlAt1(url, tag); };
const urlAt1 = (url, tag) => url.replace(/^(https:\/\/raw\.githubusercontent\.com\/[^/]+\/[^/]+\/)[^/]+\//, `$1${tag}/`).replace('/raw/branch/master/', `/raw/tag/${tag}/`);
function tagsOf(r) {
  const out = execFileSync('git', ['ls-remote', '--tags', '--refs', r.versions.git], { encoding: 'utf8', timeout: 120000 });
  return out.split('\n').map((l) => l.split('refs/tags/')[1]).filter((t) => t && r.versions.tags.test(t)).sort(natural).slice(-(r.versions.keep || KEEP));
}
if (fetch) {
  const get = (dir, files, tag, git) => {
    for (const f of files || []) {
      if (!f.url) continue; // a clone the reader's notes describe
      const out = path.join(dir, f.as); fs.mkdirSync(path.dirname(out), { recursive: true });
      // f.alt: where the same file was in older releases (tried in order at a tag)
      const tries = tag ? [f.url, ...(f.alt || [])].map((u) => urlAt(u, tag, git)) : [f.url];
      if (!tries.some((u) => { try { execFileSync('curl', ['-sSfL', u, '-o', out], { stdio: 'ignore' }); return true; } catch { return false; } })) { fs.rmSync(out, { force: true }); console.error('could not fetch', tag || '', f.url); }
    }
  };
  for (const r of readers) {
    const dir = path.join(root, r.id); fs.mkdirSync(dir, { recursive: true });
    if (!process.argv.includes('--tags-only')) get(dir, r.files); // --tags-only: the releases, the newest kept as fetched
    if (!r.versions) continue;
    let tags = []; try { tags = tagsOf(r); } catch (e) { console.error(r.id, 'tags:', e.message); }
    fs.writeFileSync(path.join(root, r.id + '@tags.json'), JSON.stringify(tags));
    for (const t of tags) get(path.join(root, `${r.id}@${t}`), r.files, t, r.versions.git);
  }
  process.exit(0);
}
const db = { note: 'Generated by tools/game-settings/gen.js from the emulators\' source. Do not edit by hand.', versions: {} };
const idOf = (e) => `${e.s}|${e.k}`;
const SAME = ['t', 'd', 'o', 'min', 'max'];
for (const r of readers) {
  try { db[r.id] = r.read(path.join(root, r.id)); } catch (e) { console.error(r.id, 'failed:', e.message); process.exitCode = 1; continue; }
  const n = Array.isArray(db[r.id]) ? db[r.id].length : Object.keys(db[r.id]).length;
  console.log(r.id, n);
  if (!r.versions || !Array.isArray(db[r.id])) continue;
  let tags = []; try { tags = JSON.parse(fs.readFileSync(path.join(root, r.id + '@tags.json'), 'utf8')); } catch {}
  const now = new Map(db[r.id].map((e) => [idOf(e), e])), V = { tags: [], diff: {} };
  for (const t of tags) {
    const tdir = path.join(root, `${r.id}@${t}`), lack = (r.files || []).filter((f) => f.url && !fs.existsSync(path.join(tdir, f.as)));
    if (lack.length) { console.error(' ', r.id, t, 'skipped: not in that release:', lack.map((f) => f.as).join(', ')); continue; } // never half-read
    let old; try { old = r.read(tdir); } catch (e) { console.error(r.id, t, 'skipped:', e.message); continue; }
    if (!Array.isArray(old) || old.length < n / 3) { console.error(r.id, t, 'skipped: too little read'); continue; }
    const d = {}, was = new Map(old.map((e) => [idOf(e), e]));
    for (const [k, e] of now) { const o = was.get(k); if (!o) d[k] = 0; else if (SAME.some((f) => JSON.stringify(o[f]) !== JSON.stringify(e[f]))) d[k] = Object.fromEntries(SAME.filter((f) => o[f] !== undefined).map((f) => [f, o[f]])); }
    for (const [k, o] of was) if (!now.has(k)) d[k] = { ...o, gone: 1 }; // only in that release
    V.tags.push(t); V.diff[t] = d;
    console.log(' ', r.id, t, Object.keys(d).length, 'differ');
  }
  if (V.tags.length) db.versions[r.id] = V;
}
fs.writeFileSync(path.join(__dirname, '../../electron/emuSettingsDb.json'), JSON.stringify(db).replace(/\},\{/g, '},\n{') + '\n');
