// Builds electron/emuSettingsDb.json: every setting each emulator takes in a game's own settings file, read from the
// emulators' source (0.9.61, owner: PPSSPP's list was wrong, Dolphin's missed most; then "across the board"). One
// reader per emulator in readers/ (what it reads and where from: its `files`, notes in docs/game-settings/<emu>.md).
// Each entry: { s: section as the game's file writes it, k: key, t: bool|int|float|enum|text, d: default as written,
// o: [[value, label]], min, max, l: the emulator's own name for it, desc, tab, adv: advanced (goes in Advanced) }.
// Usage: node tools/game-settings/gen.js --fetch <sources folder>   (downloads each reader's files into <folder>/<id>)
//        node tools/game-settings/gen.js <sources folder>
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const fetch = process.argv[2] === '--fetch';
const root = process.argv[fetch ? 3 : 2];
if (!root) { console.error('usage: node tools/game-settings/gen.js [--fetch] <sources folder>'); process.exit(1); }
const readers = fs.readdirSync(path.join(__dirname, 'readers')).filter((f) => f.endsWith('.js')).sort().map((f) => require(path.join(__dirname, 'readers', f)));
if (fetch) {
  for (const r of readers) {
    const dir = path.join(root, r.id); fs.mkdirSync(dir, { recursive: true });
    for (const f of r.files || []) {
      if (!f.url) continue; // a clone the reader's notes describe
      const out = path.join(dir, f.as); fs.mkdirSync(path.dirname(out), { recursive: true });
      try { execFileSync('curl', ['-sSfL', f.url, '-o', out]); } catch { console.error('could not fetch', f.url); }
    }
  }
  process.exit(0);
}
const db = { note: 'Generated by tools/game-settings/gen.js from the emulators\' source. Do not edit by hand.' };
for (const r of readers) {
  try { db[r.id] = r.read(path.join(root, r.id)); } catch (e) { console.error(r.id, 'failed:', e.message); process.exitCode = 1; continue; }
  const n = Array.isArray(db[r.id]) ? db[r.id].length : Object.keys(db[r.id]).length;
  console.log(r.id, n);
}
fs.writeFileSync(path.join(__dirname, '../../electron/emuSettingsDb.json'), JSON.stringify(db).replace(/\},\{/g, '},\n{') + '\n');
